image: python:3.9

stages:
  - test
  - lint
  - typecheck

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest tests/

lint:
  stage: lint
  script:
    - flake8 src/ tests/

typecheck:
  stage: typecheck
  script:
    - mypy src/ tests/