pipeline {
    agent {
        docker { 
            image 'python:3.9'
        }
    }
    environment {
        HOME = "${env.WORKSPACE}@tmp"
        BIN_PATH = "${HOME}/.local/bin/"
    }
    stages {
        stage('Prepare') {
            steps {
                sh 'python -V'
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest tests/'
            }
        }
        stage('Lint') {
            steps {
                sh 'flake8 src/ tests/'
            }
        }
        stage('Typecheck') {
            steps {
                sh 'mypy src/ tests/'
            }
        }
    }
}