pipeline {
    agent {
        docker {
            image 'python:3.9'
        }
    }
    environment {
        HOME = "${env.WORKSPACE}@tmp"
        BIN_PATH = "${HOME}/.local/bin/"
    }
    stages {
        stage('Git Clone') {
            steps {
                git url: 'http://gitlab.devops.ru/kaktuz2000/lab4.git', credentialsId: '11382cacce21e44f67b4a0b4e5c3d490c4'
            }
        }
        
    }
}