pipeline {
    agent {
        docker {
            image 'python:3.9'
        }
    }
    environment {
        HOME = "${env.WORKSPACE}@tmp"
        BIN_PATH = "${HOME}/.local/bin/"
    }
    stages {
        stage('Git Clone') {
            steps {
                git changelog: false, url: 'http://gitlab.devops.ru/kaktuz2000/lab4.git'
            }
        }
        stage('Prepare') {
            steps {
                sh 'python --version'
                sh 'pip install virtualenv'
                sh '${BIN_PATH}virtualenv venv'
                sh 'bash -c "source venv/bin/activate"'
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest tests/'
            }
        }
        stage('Lint') {
            steps {
                sh 'flake8 src/ tests/'
            }
        }
        stage('Typecheck') {
            steps {
                sh 'mypy src/ tests/'
            }
        }
    }
}